# Generated by Django 5.1.3 on 2024-11-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_student_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='core/cake.jpg', upload_to='core/images'),
        ),
    ]
